---
title: "Worked Example 3 - Cohort Setup"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Worked Example 3 - Cohort Setup}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This is an example of how to take data output from main population calculations and use it to set up the details of the trial cohort. 

First load the package (install it first if necessary as shown in the [Installation article](https://keithjf82.github.io/vectorpower/articles/B_installation.html):

```{r setup}
library(vectorpower)
```

In this example, the main population data is loaded from an RDS file.

```{r, eval = FALSE}
mainpop_data <- readRDS(file=url("https://github.com/KeithJF82/vectorpower/raw/master/inst/extdata/mainpop_data1.Rds"))
```



```{r, eval = FALSE}
setup_list_con <- cluster_input_setup(input_list=mainpop_data, set_n_pt=1, set_n_int=1,
                                      benchmark = "EIR_annual", age_start=0.0, age_end=65.0)
cluster_list_con <- clusters_create(input_list=setup_list_con,n_clusters=100,
                                    benchmark_mean=3.1, benchmark_stdev=0.5, int_mean=0.0, int_stdev=0.0)
```



```{r, eval = FALSE}
setup_list_int <- cluster_input_setup(input_list=mainpop_data, set_n_pt=1, set_n_int=1,
                                      benchmark = "EIR_annual", age_start=0.0, age_end=65.0)
cluster_list_int <- clusters_create(input_list=setup_list_int,n_clusters=100,
                                    benchmark_mean=3.1, benchmark_stdev=0.5,int_mean=0.1, int_stdev=0.0)
```





