# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_cohort <- function(params, trial_params, cluster_data) {
    .Call(`_vectorpower_rcpp_cohort`, params, trial_params, cluster_data)
}

rcpp_cohort2 <- function(params, trial_params, cluster_data) {
    .Call(`_vectorpower_rcpp_cohort2`, params, trial_params, cluster_data)
}

rcpp_ento <- function(params, inputs, trial_params) {
    .Call(`_vectorpower_rcpp_ento`, params, inputs, trial_params)
}

rcpp_mainpop <- function(params, inputs, trial_params) {
    .Call(`_vectorpower_rcpp_mainpop`, params, inputs, trial_params)
}

rcpp_mainpop_ss <- function(params, trial_params) {
    .Call(`_vectorpower_rcpp_mainpop_ss`, params, trial_params)
}

