# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_cohort <- function(params, cohort_params) {
    .Call(`_vectorpower_rcpp_cohort`, params, cohort_params)
}

dummy1_cpp <- function(args) {
    .Call(`_vectorpower_dummy1_cpp`, args)
}

rcpp_mainpop <- function(params, trial_params) {
    .Call(`_vectorpower_rcpp_mainpop`, params, trial_params)
}

